### ISSUE TITLE
Firmware version display

### ISSUE THREAD

**Issue by schorsch3000** [dithmer/snes2c64-gui#1]
when the firmware command to show current firmware version is implemented we should display the installed and current firmware version in the gui

**Comment by dithmer** [comment]
We should also include a killswitch, which is activated on incompatible GUI <-> firmware versions. (Or at least show up a big warning)

**Comment by dithmer** [comment]
> We should also include a killswitch, which is activated on incompatible GUI <-> firmware versions. (Or at least show up a big warning)

#12
